import type { Item } from '@/types'

export const items: Item[] = [
  {
    id: 'slime',
    name: 'Slime',
    type: 'animal',
    seasons: ['any'],
    sources: ['Drop from Slimes'],
  },
  {
    id: 'bat-wing',
    name: 'Bat Wing',
    type: 'animal',
    seasons: ['any'],
    sources: ['Drop from Bats in the Mines and Skull Cavern'],
  },
  {
    id: 'duck-feather',
    name: 'Duck Feather',
    type: 'animal',
    seasons: ['any'],
    sources: ['Drop from Ducks'],
    notes: 'Minimum of 1 Heart Friendship required.',
  },
  {
    id: 'rabbits-foot',
    name: "Rabbit's Foot",
    type: 'animal',
    seasons: ['any'],
    sources: ['Drop from Rabbits', 'Drop from Serpents in Skull Cavern (0.8%)'],
  },
  {
    id: 'large-milk',
    name: 'Large Milk',
    type: 'animal',
    seasons: ['any'],
    sources: ['Cows'],
    notes: 'Need to have a high friendship level',
  },
  {
    id: 'large-brown-egg',
    name: 'Large Brown Egg',
    type: 'animal',
    seasons: ['any'],
    sources: ['Drop from Brown Chickens'],
    notes: 'Need to have a high friendship level',
  },
  {
    id: 'large-white-egg',
    name: 'Large White Egg',
    type: 'animal',
    seasons: ['any'],
    sources: ['Drop from White Chickens'],
    notes: 'Need to have a high friendship level',
  },
  {
    id: 'large-goat-milk',
    name: 'Large Goat Milk',
    type: 'animal',
    seasons: ['any'],
    sources: ['Goats'],
    notes: 'Need to have a high friendship level',
  },
  {
    id: 'wool',
    name: 'Wool',
    type: 'animal',
    seasons: ['any'],
    sources: ['Sheep', 'Rabbits'],
  },
  {
    id: 'duck-egg',
    name: 'Duck Egg',
    type: 'animal',
    seasons: ['any'],
    sources: ['Drop from Ducks'],
  },
]
