import type { Item } from '@/types/bundles'

export const items: Item[] = [
  {
    id: 'parsnip',
    name: 'Parsnip',
    type: 'crop',
    seasons: ['spring'],
    sources: ['Spring Crops'],
  },
  {
    id: 'green-bean',
    name: 'Green Bean',
    type: 'crop',
    seasons: ['spring'],
    sources: ['Spring Crops'],
  },
  {
    id: 'cauliflower',
    name: 'Cauliflower',
    type: 'crop',
    seasons: ['spring'],
    sources: ['Spring Crops'],
  },
  {
    id: 'potato',
    name: 'Potato',
    type: 'crop',
    seasons: ['spring'],
    sources: ['Spring Crops'],
  },
  {
    id: 'tomato',
    name: 'Tomato',
    type: 'crop',
    seasons: ['summer'],
    sources: ['Summer Crops'],
  },
  {
    id: 'hot-pepper',
    name: 'Hot Pepper',
    type: 'crop',
    seasons: ['summer'],
    sources: ['Summer Crops'],
  },
  {
    id: 'blueberry',
    name: 'Blueberry',
    type: 'crop',
    seasons: ['summer'],
    sources: ['Summer Crops'],
  },
  {
    id: 'melon',
    name: 'Melon',
    type: 'crop',
    seasons: ['summer'],
    sources: ['Summer Crops'],
  },
  {
    id: 'corn',
    name: 'Corn',
    type: 'crop',
    seasons: ['summer', 'fall'],
    sources: ['Summer Crops', 'Fall Crops'],
  },
  {
    id: 'eggplant',
    name: 'Eggplant',
    type: 'crop',
    seasons: ['fall'],
    sources: ['Fall Crops'],
  },
  {
    id: 'pumpkin',
    name: 'Pumpkin',
    type: 'crop',
    seasons: ['fall'],
    sources: ['Fall Crops'],
  },
  {
    id: 'yam',
    name: 'Yam',
    type: 'crop',
    seasons: ['fall'],
    sources: ['Fall Crops'],
  },
  {
    id: 'apple',
    name: 'Apple',
    type: 'crop',
    seasons: ['fall'],
    sources: ['Apple Trees during Fall', 'Farm Cave (fruit bat option)'],
    notes: 'Apple Tree must be planted prior to Fall',
  },
  {
    id: 'apricot',
    name: 'Apricot',
    type: 'crop',
    seasons: ['spring'],
    sources: ['Apricot Trees during Spring', 'Farm cave (fruit bat option)'],
    notes: 'Apricot Tree must be planted prior to Spring. Not achievable in Year 1.',
  },
  {
    id: 'orange',
    name: 'Orange',
    type: 'crop',
    seasons: ['summer'],
    sources: ['Orange Trees during Summer', 'Farm cave (fruit bat option)'],
    notes: 'Orange Tree must be planted prior to Summer.',
  },
  {
    id: 'peach',
    name: 'Peach',
    type: 'crop',
    seasons: ['summer'],
    sources: ['Peach Tree during Summer', 'Farm cave (fruit bat option)'],
    notes: 'Peach Tree must be planted prior to Summer.',
  },
  {
    id: 'pomegranate',
    name: 'Pomegranate',
    type: 'crop',
    seasons: ['fall'],
    sources: ['Pomegranate Tree during Fall', 'Farm cave (fruit bat option)'],
  },
  {
    id: 'cherry',
    name: 'Cherry',
    type: 'crop',
    seasons: ['any'],
    sources: ['Cherry Tree during Spring', 'Farm cave (fruit bat option)'],
    notes: 'Cherry Tree must be planted prior to Spring. Not achievable in Year 1.',
  },
  {
    id: 'poppy',
    name: 'Poppy',
    type: 'crop',
    seasons: ['summer'],
    sources: ['Summer Crops'],
  },
  {
    id: 'sunflower',
    name: 'Sunflower',
    type: 'crop',
    seasons: ['summer', 'fall'],
    sources: ['Summer / Fall Crops'],
  },
  {
    id: 'red-cabbage',
    name: 'Red Cabbage',
    type: 'crop',
    seasons: ['summer'],
    sources: ['Summer Crops (seeds sold by Pierre in Year 2+)', 'Sold by Traveling Cart'],
  },
  {
    id: 'wheat',
    name: 'Wheat',
    type: 'crop',
    seasons: ['summer', 'fall'],
    sources: ['Summer / Fall Crops'],
  },
  {
    id: 'hay',
    name: 'Hay',
    type: 'crop',
    seasons: ['any'],
    sources: [
      "Sold by Marnie's Ranch or Desert Trader",
      'Harvest from Grass or Wheat using a Scythe',
    ],
  },
]
