import type { Item } from '@/types/bundles'

export const items: Item[] = [
  {
    id: 'sunfish',
    name: 'Sunfish',
    type: 'fish',
    seasons: ['spring', 'summer'],
    sources: ['River | Sunny | 6am - 7pm | Spring and Summer'],
  },
  {
    id: 'catfish',
    name: 'Catfish',
    type: 'fish',
    seasons: ['spring', 'summer', 'fall'],
    sources: [
      'River | Raining | 6am - Midnight | Spring and Fall',
      'Secret Woods | Raining | 6am - Midnight | Summer',
    ],
  },
  {
    id: 'shad',
    name: 'Shad',
    type: 'fish',
    seasons: ['spring', 'summer', 'fall'],
    sources: ['River | Raining | 9am - 2am | Spring, Summer, and Fall'],
  },
  {
    id: 'tiger-trout',
    name: 'Tiger Trout',
    type: 'fish',
    seasons: ['fall', 'winter'],
    sources: ['River | 6am - 7pm | Fall and Winter'],
  },
  {
    id: 'largemouth-bass',
    name: 'Largemouth Bass',
    type: 'fish',
    seasons: ['any'],
    sources: ['Lake | 6am - 7pm | All Seasons'],
  },
  {
    id: 'carp',
    name: 'Carp',
    type: 'fish',
    seasons: ['any'],
    sources: [
      'Lake | 6am - 2am | Spring, Summer, and Fall',
      'Secret Woods or Sewer | 6am - 2am | All Seasons',
    ],
  },
  {
    id: 'bullhead',
    name: 'Bullhead',
    type: 'fish',
    seasons: ['any'],
    sources: ['Lake | 6am - 2am | All Seasons'],
  },
  {
    id: 'sturgeon',
    name: 'Sturgeon',
    type: 'fish',
    seasons: ['summer', 'winter'],
    sources: ['Lake | 6am - 7pm | Summer and Winter'],
  },
  {
    id: 'sardine',
    name: 'Sardine',
    type: 'fish',
    seasons: ['spring', 'fall', 'winter'],
    sources: ['Ocean | 6am - 7pm | Spring, Fall, and Winter'],
  },
  {
    id: 'tuna',
    name: 'Tuna',
    type: 'fish',
    seasons: ['summer', 'winter'],
    sources: ['Ocean | 6am - 7pm | Summer and Winter'],
  },
  {
    id: 'red-snapper',
    name: 'Red Snapper',
    type: 'fish',
    seasons: ['summer', 'fall'],
    sources: ['Ocean | Raining | 6am - 7pm | Summer and Fall'],
  },
  {
    id: 'tilapia',
    name: 'Tilapia',
    type: 'fish',
    seasons: ['summer', 'fall'],
    sources: ['Ocean | 6am - 2am | Summer and Fall'],
  },
  {
    id: 'walleye',
    name: 'Walleye',
    type: 'fish',
    seasons: ['fall', 'winter'],
    sources: ['River | Raining | 12pm - 2am | Fall and Winter'],
  },
  {
    id: 'bream',
    name: 'Bream',
    type: 'fish',
    seasons: ['any'],
    sources: ['River | 6pm - 2am | All Seasons'],
  },
  {
    id: 'eel',
    name: 'Eel',
    type: 'fish',
    seasons: ['spring', 'fall'],
    sources: ['Ocean | Raining | 4pm - 2am | Spring or Fall'],
  },
  {
    id: 'lobster',
    name: 'Lobster',
    type: 'fish',
    seasons: ['any'],
    sources: ['Caught in Crab Pots (ocean)'],
  },
  {
    id: 'crayfish',
    name: 'Crayfish',
    type: 'fish',
    seasons: ['any'],
    sources: ['Caught in Crab Pots (freshwater)'],
  },
  {
    id: 'crab',
    name: 'Crab',
    type: 'fish',
    seasons: ['any'],
    sources: ['Caught in Crab Pots (ocean)', 'Drop from Rock Crabs or Lava Crabs in the Mines'],
  },
  {
    id: 'cockle',
    name: 'Cockle',
    type: 'fish',
    seasons: ['any'],
    sources: ['Caught in Crab Pots (ocean)', 'Beach Foraging'],
  },
  {
    id: 'mussel',
    name: 'Mussel',
    type: 'fish',
    seasons: ['any'],
    sources: ['Caught in Crab Pots (ocean)', 'Beach Foraging'],
  },
  {
    id: 'shrimp',
    name: 'Shrimp',
    type: 'fish',
    seasons: ['any'],
    sources: ['Caught in Crab Pots (ocean)'],
  },
  {
    id: 'snail',
    name: 'Snail',
    type: 'fish',
    seasons: ['any'],
    sources: ['Caught in Crab Pots (freshwater)'],
  },
  {
    id: 'periwinkle',
    name: 'Periwinkle',
    type: 'fish',
    seasons: ['any'],
    sources: ['Caught in Crab Pots (freshwater)'],
  },
  {
    id: 'oyster',
    name: 'Oyster',
    type: 'fish',
    seasons: ['any'],
    sources: ['Caught in Crab Pots (ocean)', 'Beach Foraging'],
  },
  {
    id: 'clam',
    name: 'Clam',
    type: 'fish',
    seasons: ['any'],
    sources: ['Caught in Crab Pots (ocean)', 'Beach Foraging'],
  },
  {
    id: 'pufferfish',
    name: 'Pufferfish',
    type: 'fish',
    seasons: ['summer'],
    sources: ['Ocean | Sunny | 12pm - 4pm | Summer', 'Purchased from the Traveling Cart'],
  },
  {
    id: 'ghostfish',
    name: 'Ghostfish',
    type: 'fish',
    seasons: ['any'],
    sources: ['Mines (20, 60)', 'Drop from Ghosts'],
  },
  {
    id: 'woodskip',
    name: 'Woodskip',
    type: 'fish',
    seasons: ['any'],
    sources: ['Secret Woods | 6am - 2am | All Seasons', 'Purchased from Traveling Cart'],
  },
  {
    id: 'chub',
    name: 'Chub',
    type: 'fish',
    seasons: ['any'],
    sources: ['Lake | 6am - 2am | All Seasons'],
  },
]
