import type { Item } from '@/types'

export const items: Item[] = [
  {
    id: 'wild-horseradish',
    name: 'Wild Horseradish',
    type: 'forage',
    seasons: ['spring'],
    sources: ['Spring Foraging'],
  },
  {
    id: 'daffodil',
    name: 'Daffodil',
    type: 'forage',
    seasons: ['spring'],
    sources: ['Spring Foraging', "Pierre's Shop at the Flower Dance"],
  },
  {
    id: 'leek',
    name: 'Leek',
    type: 'forage',
    seasons: ['spring'],
    sources: ['Spring Foraging'],
  },
  {
    id: 'dandelion',
    name: 'Dandelion',
    type: 'forage',
    seasons: ['spring'],
    sources: ['Spring Foraging', "Pierre's Shop at the Flower Dance"],
  },
  {
    id: 'grape',
    name: 'Grape',
    type: 'forage',
    seasons: ['summer'],
    sources: ['Summer Foraging', 'Summer Crop'],
    notes: 'Can also be grown as a crop.',
  },
  {
    id: 'spice-berry',
    name: 'Spice Berry',
    type: 'forage',
    seasons: ['summer'],
    sources: ['Summer Foraging'],
  },
  {
    id: 'sweet-pea',
    name: 'Sweet Pea',
    type: 'forage',
    seasons: ['summer'],
    sources: ['Summer Foraging'],
  },
  {
    id: 'common-mushroom',
    name: 'Common Mushroom',
    type: 'forage',
    seasons: ['fall'],
    sources: ['Fall Foraging', 'Farm Cave (mushroom option)'],
  },
  {
    id: 'wild-plum',
    name: 'Wild Plum',
    type: 'forage',
    seasons: ['fall'],
    sources: ['Fall Foraging'],
  },
  {
    id: 'hazelnut',
    name: 'Hazelnut',
    type: 'forage',
    seasons: ['fall'],
    sources: ['Fall Foraging'],
  },
  {
    id: 'blackberry',
    name: 'Blackberry',
    type: 'forage',
    seasons: ['fall'],
    sources: ['Fall Foraging'],
    notes: 'On bushes between Fall 8th-11th',
  },
  {
    id: 'winter-root',
    name: 'Winter Root',
    type: 'forage',
    seasons: ['any'],
    sources: ['Winter Foraging', 'Mines (41-79) - Drop from Slimes'],
  },
  {
    id: 'crystal-fruit',
    name: 'Crystal Fruit',
    type: 'forage',
    seasons: ['any'],
    sources: ['Winter Foraging', 'Mines (41-79) - Drop from Coal Sprites'],
  },
  {
    id: 'snow-yam',
    name: 'Snow Yam',
    type: 'forage',
    seasons: ['winter'],
    sources: ['Tilling soil or Artifact spots during Winter.'],
  },
  {
    id: 'crocus',
    name: 'Crocus',
    type: 'forage',
    seasons: ['winter'],
    sources: ['Winter Foraging'],
  },
  {
    id: 'coconut',
    name: 'Coconut',
    type: 'forage',
    seasons: ['any'],
    sources: ['Foraging in the Desert'],
  },
  {
    id: 'cactus-fruit',
    name: 'Cactus Fruit',
    type: 'forage',
    seasons: ['any'],
    sources: ['Foraging in the Desert'],
  },
  {
    id: 'cave-carrot',
    name: 'Cave Carrot',
    type: 'forage',
    seasons: ['any'],
    sources: ['Crates in the Mines', 'Tilling soil in the Mines'],
    notes: 'Often found on floors 10-20',
  },
  {
    id: 'red-mushroom',
    name: 'Red Mushroom',
    type: 'forage',
    seasons: ['any'],
    sources: ['Foraging in the Mines', 'Farm cave (mushroom option)'],
  },
  {
    id: 'purple-mushroom',
    name: 'Purple Mushroom',
    type: 'forage',
    seasons: ['any'],
    sources: ['Foraging in the Mines', 'Farm cave (mushroom option)'],
  },
  {
    id: 'maple-syrup',
    name: 'Maple Syrup',
    type: 'forage',
    seasons: ['any'],
    sources: ['Harvested from maple trees using a Tapper'],
  },
  {
    id: 'oak-resin',
    name: 'Oak Resin',
    type: 'forage',
    seasons: ['any'],
    sources: ['Harvested from oak trees using a Tapper'],
  },
  {
    id: 'pine-tar',
    name: 'Pine Tar',
    type: 'forage',
    seasons: ['any'],
    sources: ['Harvested from pine trees using a Tapper'],
  },
  {
    id: 'morel',
    name: 'Morel',
    type: 'forage',
    seasons: ['any'],
    sources: ['Farm cave (mushroom option)'],
  },
  {
    id: 'fiddlehead-fern',
    name: 'Fiddlehead Fern',
    type: 'forage',
    seasons: ['summer'],
    sources: ['Summer Foraging in Secret Woods'],
  },
  {
    id: 'truffle',
    name: 'Truffle',
    type: 'forage',
    seasons: ['any'],
    sources: ['Found by happy pigs while outdoors'],
  },
  {
    id: 'sea-urchin',
    name: 'Sea Urchin',
    type: 'forage',
    seasons: ['any'],
    sources: ['Beach Foraging, after fixing the bridge to the tide pools'],
  },
  {
    id: 'nautilus-shell',
    name: 'Nautilus Shell',
    type: 'forage',
    seasons: ['winter'],
    sources: ['Winter Beach Foraging'],
  },
]
